---
- name: 'Instala pacotes de dependencia do sistema operacional'
  apt:
    name:
      - mysql-server-5.6
      - python-mysqldb
    state: latest
  become: yes

- name: 'Cria o banco do MySQL'
  mysql_db: 
    name: "{{ wp_db_name }}"
    login_user: root
    state: present

- name: 'Cria o usuário do MySQL'
  no_log: true
  mysql_user:
    login_user: root
    name: "{{ wp_username }}"
    password: "{{ wp_user_password }}"
    priv: "{{ wp_db_name }}.*:ALL"
    state: present
    update_password: always
    host: "{{ item }}"
  with_items:
    - "localhost"
    - '127.0.0.1'
    - "{{ wp_host_ip }}"

- name: 'Configura MySQL para aceitar conexões remotas'
  replace:
    path: '/etc/mysql/my.cnf'
    after: 'bind-address\s+=\s+'
    before: "\n"
    regexp: "^127\\.0\\.0\\.1$"
    replace: "0.0.0.0"
    backup: yes
  become: yes
  notify:
    - restart mysql    

# - name: Allow all access to tcp port 3306 from local and wp_host_ip
#   ufw:
#     rule: allow
#     port: '3306'
#     proto: tcp
#     from_ip: '{{ item }}'
#   become: yes
#   loop:
#     - 127.0.0.1/32
#     - "{{ wp_host_ip }}"/32